### ISSUE TITLE
runserver error in vagrant

### ISSUE THREAD

**Issue by kjaebker** [roundware/roundware-server#221]
I am trying to get this up and running locally and keep getting the following error when running scripts/runserver.sh

I followed the install steps as listed and even tried moving the file onto the sys.path with no luck.

Here is the error:

Traceback (most recent call last):
  File "/home/vagrant/roundware-server/roundware/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'roundware.settings.dev' (Is it on sys.path? Is there an import error in the settings file?): No module named roundware.settings.dev

**Comment by eosrei** [comment]
In general this happens if the PYTHONPATH is wrong. It is set at login by .profile. I can fix in 3/9

**Comment by eosrei** [comment]
The `install.sh` script was missing a `mkdir`. This issue is corrected by #222.
