### ISSUE TITLE
ensure adding asset doesn't fail just because notification email fails

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#336]
Currently, if the notification email credentials are incorrect or if the send quota is reached for the notification account, the entire add asset process fails.

Response from the latter:
```
{u'detail': u"(550, '5.4.5 Daily user sending quota exceeded. c4sm5921393ioc.18 - gsmtp')"}
```

This is obviously not good. Instead, the asset should be added per the normal process and some kind of notification that the notifications are broken should happen. Not sure how the latter could happen given its meta nature, but something to think about.

**Comment by hburgund** [comment]
@jslootbeek since you built the notifications initially, do you have any idea why this might be happening or have suggestions as to how to fix? I've had a quick look at the notifications code, but haven't seen why the process is terminated if the email fails rather than doing something more graceful.

**Comment by jslootbeek** [comment]
Is there a stacktrace you can share?

**Comment by hburgund** [comment]
This is long, but hopefully useful. This is generated when I have an asset edit notification setup and proceed to try to edit an asset. I purposefully set the email of the notification recipient user to blank to generate the error for testing purposes.

Ideally, the error would somehow be logged, but the actual editing of the asset would still happen despite the notification failing. There is no reason for the notification email to be on the critical path.

```
[24/Jul/2017 22:09:07] "GET /admin/rw/asset/ HTTP/1.1" 200 80878
22:09:16 ERROR <django.request.handle_uncaught_exception:284> Internal Server Error: /admin/rw/asset/
Traceback (most recent call last):
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/vagrant/roundware/rw/admin.py", line 163, in changelist_view
    return super(AssetAdmin, self).changelist_view(request, extra_context=extra_context)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1531, in changelist_view
    self.save_model(request, obj, form, change=True)
  File "/vagrant/roundware/rw/admin.py", line 174, in save_model
    obj.save()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/vagrant/roundware/rw/models.py", line 230, in save
    force_insert, force_update, using, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/vagrant/roundware/notifications/__init__.py", line 54, in send_notifications_add_edit
    n.notify(ref=instance.id)
  File "/vagrant/roundware/notifications/models.py", line 90, in notify
    ret = email.send()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'': (555, '5.5.2 Syntax error. q185sm8893718qkb.45 - gsmtp')}
Internal Server Error: /admin/rw/asset/
Traceback (most recent call last):
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/vagrant/roundware/rw/admin.py", line 163, in changelist_view
    return super(AssetAdmin, self).changelist_view(request, extra_context=extra_context)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1531, in changelist_view
    self.save_model(request, obj, form, change=True)
  File "/vagrant/roundware/rw/admin.py", line 174, in save_model
    obj.save()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/vagrant/roundware/rw/models.py", line 230, in save
    force_insert, force_update, using, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/vagrant/roundware/notifications/__init__.py", line 54, in send_notifications_add_edit
    n.notify(ref=instance.id)
  File "/vagrant/roundware/notifications/models.py", line 90, in notify
    ret = email.send()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'': (555, '5.5.2 Syntax error. q185sm8893718qkb.45 - gsmtp')}
22:09:16 ERROR <django.request.handle_uncaught_exception:284> Internal Server Error: /admin/rw/asset/
Traceback (most recent call last):
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/vagrant/roundware/rw/admin.py", line 163, in changelist_view
    return super(AssetAdmin, self).changelist_view(request, extra_context=extra_context)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1531, in changelist_view
    self.save_model(request, obj, form, change=True)
  File "/vagrant/roundware/rw/admin.py", line 174, in save_model
    obj.save()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/vagrant/roundware/rw/models.py", line 230, in save
    force_insert, force_update, using, *args, **kwargs)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/vagrant/roundware/notifications/__init__.py", line 54, in send_notifications_add_edit
    n.notify(ref=instance.id)
  File "/vagrant/roundware/notifications/models.py", line 90, in notify
    ret = email.send()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'': (555, '5.5.2 Syntax error. q185sm8893718qkb.45 - gsmtp')}
```

**Comment by hburgund** [comment]
It seems like we just have to properly catch and handle the error so it doesn't stop the entire process; I just haven't been able to locate the proper spot for this yet...

We are using django's `post_save` signal to trigger the action after the asset record is saved, but it doesn't make sense to me that the record apparently isn't actually saved when the notification process is kicked off and fails. I thought that `post_save` signals trigger actions to happen once the save operation is completed, but evidence suggests otherwise.

**Comment by jslootbeek** [comment]
You'd want to catch an exception on this line, or at least make sure the return is good. 
File "/vagrant/roundware/notifications/models.py", line 90, in notify ret = email.send()

**Comment by hburgund** [comment]
Bingo :-) Now I just need to figure out how to print the smtp error in the RW logs and all will be good...thx.
```
try:
    ret = email.send()
    logger.info("Email Sent: %(email)s, %(ret)s" %
            {'email': email.to, 'ret': ret})
except:
    logger.info("EMAIL SEND FAILED :-(")
```
