### ISSUE TITLE
"AttributeError: 'module' object has no attribute" when tags are not valid

### ISSUE THREAD

**Issue by eosrei** [roundware/roundware-server#84]
When calling: operation=modify_stream&session_id=2891&tags=3,5,8 A D-Bus Exception can occur if client tag id numbers are out of date.

    2014-06-17 18:40:49,942 connection.py:234 ERROR Exception in handler for D-Bus signal:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
        self._handler(*args, **kwargs)
      File "/home/vagrant/roundware-server/roundwared/rounddbus.py", line 41, in handler
        stream.modify_stream(request)
      File "/home/vagrant/roundware-server/roundwared/stream.py", line 128, in modify_stream
        self.refresh_recordings()
      File "/home/vagrant/roundware-server/roundwared/stream.py", line 151, in refresh_recordings
    self.recordingCollection.nearby_unplayed_recordings = getattr(asset_sorters, tag.filter)(assets=self.recordingCollection.all_recordings, request=self.request)
    AttributeError: 'module' object has no attribute '--'

Issue may be low priority if difficult for client devices to cause.

**Comment by hburgund** [comment]
fixed by: https://github.com/roundware/roundware-server/commit/1d640f931e3aaec4b346d269e386f71982a27df4
